// 100 Nautical Armor Array
const FISHER_ARMOR = [
  { name: "Soggy Rags", dice: 2, wpnStr: 0, wpnDef: 2, armStr: 0, armDef: 0, value: 2, icon: "🥋" },
  { name: "Sun-Bleached Canvas Wrap", dice: 50, wpnStr: 50, wpnDef: 0, armStr: 0, armDef: 0, value: 5, icon: "🥋" },
  { name: "Dried Kelp Sunder-Vest", dice: 8, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 2, value: 8, icon: "🌿" },
  { name: "Driftwood Shingles", dice: 4,
armDef: 2, armStr: 1, wpnDef: 0, wpnStr: 0, value: 12, icon: "🪵" },
  { name: "Tattered Sailcloth Tunic", 
dice: 4,
armDef: 3, armStr: 0, wpnDef: 0, wpnStr: 0, value: 15, icon: "⛵" },
  { name: "Burlap Bait Sacking", dice: 4, armDef: 2, armStr: 2, wpnDef: 0, wpnStr: 0, value: 18, icon: "🛍️" },
  { name: "Woven Eelgrass Jerkin", 
dice: 4,
armDef: 3, armStr: 1, wpnDef: 0, wpnStr: 0, value: 22, icon: "🪺" },
  { name: "River-Mud Coated Bracers", dice: 4,
armDef: 4, armStr: 0, wpnDef: 0, wpnStr: 0, value: 26, icon: "🧱" },
  { name: "Cattail Fiber Vest", 
dice: 4,
armDef: 3, armStr: 2, wpnDef: 0, wpnStr: 0, value: 30, icon: "🌾" },
  { name: "Fisherman's Oilskin Slicker", dice: 4, armDef: 4, armStr: 1, wpnDef: 0, wpnStr: 0, value: 35, icon: "🧥" },
  { name: "Braided Hemp Hauberk", dice: 4, armDef: 5, armStr: 0, wpnDef: 0, wpnStr: 0, value: 40, icon: "🪢" },
  { name: "Salt-Crusted Leather Jerkin", dice: 4, armDef: 4, armStr: 2, wpnDef: 0, wpnStr: 0, value: 45, icon: "🛡️" },
  { name: "Rawhide Fish-Skinner Apron", dice: 5, armDef: 5, armStr: 1, wpnDef: 0, wpnStr: 0, value: 50, icon: "🦺" },
  { name: "Carp Scale Cuirass", dice: 5, armDef: 6, armStr: 0, wpnDef: 0, wpnStr: 0, value: 55, icon: "🐟" },
  { name: "Twine-Bound Shell Guards", dice: 5, armDef: 5, armStr: 2, wpnDef: 0, wpnStr: 0, value: 60, icon: "🐚" },
  { name: "Crayfish Shell Vambraces", dice: 5, armDef: 6, armStr: 1, wpnDef: 0, wpnStr: 0, value: 68, icon: "🦞" },
  { name: "Whalebone Rib Slats", dice: 5, armDef: 7, armStr: 0, wpnDef: 0, wpnStr: 0, value: 75, icon: "🦴" },
  { name: "Water-Repellent Waxed Cloak", dice: 5, armDef: 6, armStr: 2, wpnDef: 0, wpnStr: 0, value: 82, icon: "🧥" },
  { name: "Marsh-Hunter Greaves", dice: 5, armDef: 7, armStr: 1, wpnDef: 0, wpnStr: 0, value: 90, icon: "𥥾" },
  { name: "River-Otter Pelt Vest", dice: 5, armDef: 6, armStr: 3, wpnDef: 0, wpnStr: 0, value: 100, icon: "🦦" },
  { name: "Braided Nylon Mesh", dice: 5, armDef: 8, armStr: 1, wpnDef: 0, wpnStr: 0, value: 110, icon: "🕸️" },
  { name: "Treated Alligator Hide", dice: 5, armDef: 7, armStr: 3, wpnDef: 0, wpnStr: 0, value: 120, icon: "🐊" },
  { name: "Dock-Worker Heavy Leather", dice: 5, armDef: 9, armStr: 1, wpnDef: 0, wpnStr: 0, value: 135, icon: "🦺" },
  { name: "Tar-Dipped Brigandine", dice: 5, armDef: 8, armStr: 3, wpnDef: 0, wpnStr: 0, value: 150, icon: "🖤" },
  { name: "Hardened Garpike Scales", dice: 5, armDef: 10, armStr: 1, wpnDef: 0, wpnStr: 0, value: 165, icon: "🐠" },
  { name: "Smuggler's Quilted Gambeson", dice:6, armDef: 9, armStr: 3, wpnDef: 0, wpnStr: 0, value: 180, icon: "👕" },
  { name: "Clam-Shell Pauldrons", dice:6, armDef: 11, armStr: 1, wpnDef: 0, wpnStr: 0, value: 200, icon: "🐚" },
  { name: "Sunken Brig Timbers", dice:6, armDef: 10, armStr: 3, wpnDef: 0, wpnStr: 0, value: 220, icon: "🪵" },
  { name: "Harpooner's Reinforced Tunic", dice:6, armDef: 11, armStr: 2, wpnDef: 0, wpnStr: 0, value: 245, icon: "🔱" },
  { name: "Sturgeon Bone Breastplate", dice:6, armDef: 12, armStr: 2, wpnDef: 0, wpnStr: 0, value: 270, icon: "🦴" },
  { name: "Gilded Nautilus Shell-Mail", dice:7, armDef: 11, armStr: 4, wpnDef: 0, wpnStr: 0, value: 300, icon: "🐚" },
  { name: "Anchor-Chain Maille Vest", dice:7, armDef: 13, armStr: 2, wpnDef: 0, wpnStr: 0, value: 330, icon: "⛓️" },
  { name: "Deep-Pool Turtle Carapace", dice:7, armDef: 14, armStr: 1, wpnDef: 0, wpnStr: 0, value: 365, icon: "🐢" },
  { name: "Coral-Encrusted Hauberk", dice:7, armDef: 13, armStr: 3, wpnDef: 0, wpnStr: 0, value: 400, icon: "🪸" },
  { name: "Shark-Skin Buff Coat", dice:7, armDef: 12, armStr: 5, wpnDef: 0, wpnStr: 0, value: 440, icon: "🦈" },
  { name: "Whaler's Heavy Iron-Stitched", dice:7, armDef: 15, armStr: 2, wpnDef: 0, wpnStr: 0, value: 480, icon: "⚓" },
  { name: "Barnacle-Plated Iron Bracers", dice:7, armDef: 14, armStr: 4, wpnDef: 0, wpnStr: 0, value: 520, icon: "🧱" },
  { name: "Black-Coral Rib Guards", dice:7, armDef: 16, armStr: 2, wpnDef: 0, wpnStr: 0, value: 570, icon: "🪸" },
  { name: "Lobster-Grip Gauntlets", dice:7, armDef: 15, armStr: 4, wpnDef: 0, wpnStr: 0, value: 620, icon: "🦞" },
  { name: "Dredger's Heavy Iron-Ribs", dice:7, armDef: 17, armStr: 2, wpnDef: 0, wpnStr: 0, value: 680, icon: "🪜" },
  { name: "Tidal-Wave Leather Mantle", dice:7, armDef: 16, armStr: 4, wpnDef: 0, wpnStr: 0, value: 740, icon: "🌊" },
  { name: "Manta-Ray Exoskin", dice:7, armDef: 15, armStr: 6, wpnDef: 0, wpnStr: 0, value: 800, icon: "🐟" },
  { name: "Corroded Diving Brass", dice:7, armDef: 18, armStr: 3, wpnDef: 0, wpnStr: 0, value: 870, icon: "🧑‍🚀" },
  { name: "Siren-Weave Cloak", dice:7, armDef: 16, armStr: 6, wpnDef: 0, wpnStr: 0, value: 950, icon: "🧜" },
  { name: "Reef-Sentry Carapace", dice:7, armDef: 19, armStr: 3, wpnDef: 0, wpnStr: 0, value: 1040, icon: "🪸" },
  { name: "Sunken Galleon Ironplates", dice:7, armDef: 20, armStr: 3, wpnDef: 0, wpnStr: 0, value: 1150, icon: "🚢" },
  { name: "Electric-Eel Insulation Tunic", dice:7, armDef: 18, armStr: 6, wpnDef: 0, wpnStr: 0, value: 1260, icon: "⚡" },
  { name: "Giant Crab Shell-Plate", dice:7, armDef: 22, armStr: 2, wpnDef: 0, wpnStr: 0, value: 1380, icon: "🦀" },
  { name: "Abyssal Pressure Suit", dice:7, armDef: 21, armStr: 4, wpnDef: 0, wpnStr: 0, value: 1500, icon: "🛡️" },
  { name: "Ghost-Ship Sail Shroud", dice:7, armDef: 20, armStr: 6, wpnDef: 0, wpnStr: 0, value: 1650, icon: "👻" },
  { name: "Sea-Leach Hide Jerkin", dice:10, armDef: 22, armStr: 5, wpnDef: 0, wpnStr: 0, value: 1800, icon: "🐲" },
  { name: "Sunken Bronze Carapace",  dice:10, armDef: 24, armStr: 3, wpnDef: 0, wpnStr: 0, value: 1950, icon: "⚜️" },
  { name: "Pearl-Studded Leather",  dice:10, armDef: 23, armStr: 5, wpnDef: 0, wpnStr: 0, value: 2150, icon: "🦪" },
  { name: "Drowned Knight Plate",  dice:10, armDef: 26, armStr: 2, wpnDef: 0, wpnStr: 0, value: 2350, icon: "🤺" },
  { name: "Abyssal Chitin Maille",  dice:10, armDef: 25, armStr: 4, wpnDef: 0, wpnStr: 0, value: 2600, icon: "🦂" },
  { name: "Trench-Dweller Great-Garb",  dice:10, armDef: 24, armStr: 6, wpnDef: 0, wpnStr: 0, value: 2850, icon: "🧥" },
  { name: "Kraken Leather Vest",  dice:10, armDef: 26, armStr: 5, wpnDef: 0, wpnStr: 0, value: 3100, icon: "🦑" },
  { name: "Leviathan Rib Slabs",  dice:10, armDef: 28, armStr: 3, wpnDef: 0, wpnStr: 0, value: 3400, icon: "🦴" },
  { name: "Arundo Silt-Weave Robes", dice:10, armDef: 25, armStr: 7, wpnDef: 0, wpnStr: 0, value: 3750, icon: "🎋" },
  { name: "Submerged Meteorite Ringmail", dice:10, armDef: 29, armStr: 4, wpnDef: 0, wpnStr: 0, value: 4100, icon: "☄️" },
  { name: "Black-Trench Exoskeleton", dice:10, armDef: 28, armStr: 6, wpnDef: 0, wpnStr: 0, value: 4500, icon: "🤖" },
  { name: "Merfolk Vanguard Maille", dice:10, armDef: 30, armStr: 5, wpnDef: 0, wpnStr: 0, value: 4900, icon: "🔱" },
  { name: "Tsunami Proof Bulwark Vest", dice:10, armDef: 32, armStr: 3, wpnDef: 0, wpnStr: 0, value: 5400, icon: "🌊" },
  { name: "Prismatic Scale Hauberk", dice:10, armDef: 30, armStr: 7, wpnDef: 0, wpnStr: 0, value: 5900, icon: "🔮" },
  { name: "Ancient Corsair Iron-Coat", dice:12, armDef: 33, armStr: 4, wpnDef: 0, wpnStr: 0, value: 6500, icon: "🏴‍☠️" },
  { name: "Deep-Sea Vent Forge-Plate", dice:12, armDef: 35, armStr: 3, wpnDef: 0, wpnStr: 0, value: 7200, icon: "🌋" },
  { name: "Kraken-Skin Dread-Cloak", dice:12, armDef: 32, armStr: 8, wpnDef: 0, wpnStr: 0, value: 8000, icon: "🐙" },
  { name: "Sunken King's Ceremonial", dice:12, armDef: 36, armStr: 4, wpnDef: 0, wpnStr: 0, value: 8800, icon: "👑" },
  { name: "Hydro-Engine Exosuit", dice:12, armDef: 38, armStr: 3, wpnDef: 0, wpnStr: 0, value: 9700, icon: "⚙️" },
  { name: "Abyssal Angler Shell", dice:12, armDef: 36, armStr: 6, wpnDef: 0, wpnStr: 0, value: 10700, icon: "🐡" },
  { name: "Elder Turtle Great-Shell", dice:12, armDef: 40, armStr: 2, wpnDef: 0, wpnStr: 0, value: 11800, icon: "🐢" },
  { name: "Maelstrom Infused Maille", dice:12, armDef: 38, armStr: 6, wpnDef: 0, wpnStr: 0, value: 13000, icon: "🌀" },
  { name: "Titan Whaler Aegis", dice:15, armDef: 42, armStr: 3, wpnDef: 0, wpnStr: 0, value: 14300, icon: "⚓" },
  { name: "Siren Queen's Silk-Weave", dice:15, armDef: 37, armStr: 10, wpnDef: 0, wpnStr: 0, value: 15800, icon: "🧜‍♀️" },
  { name: "Abyssal Obsidian Plate", dice:50, armDef: 44, armStr: 4, wpnDef: 0, wpnStr: 0, value: 17400, icon: "🖤" },
  { name: "Oceanic Hydra Skin", dice:60, armDef: 42, armStr: 7, wpnDef: 0, wpnStr: 0, value: 19200, icon: "🐉" },
  { name: "Sunken Dreadnought Ribs", dice:70, armDef: 46, armStr: 4, wpnDef: 0, wpnStr: 0, value: 21200, icon: "🚢" },
  { name: "Neptune's Guard Regalia", dice:75, armDef: 45, armStr: 6, wpnDef: 0, wpnStr: 0, value: 23500, icon: "🔱" },
  { name: "Void-Trench Carapace", dice:80, armDef: 48, armStr: 4, wpnDef: 0, wpnStr: 0, value: 26000, icon: "🌌" },
  { name: "Leviathan Scale Dread-Mail", dice:90, armDef: 46, armStr: 8, wpnDef: 0, wpnStr: 0, value: 28800, icon: "🐉" },
  { name: "Deep-Dive Prototype Rig", dice:95, armDef: 50, armStr: 5, wpnDef: 0, wpnStr: 0, value: 32000, icon: "🤿" },
  { name: "Maelstrom Core Breastplate", dice:99, armDef: 48, armStr: 9, wpnDef: 0, wpnStr: 0, value: 35500, icon: "🌀" },
  { name: "Dragon-Leach Slime-Plating", dice: 115, armDef: 52, armStr: 6, wpnDef: 0, wpnStr: 0, value: 39500, icon: "🐲" },
  { name: "Ancient Sea-God Tunic", dice: 115, armDef: 50, armStr: 10, wpnDef: 0, wpnStr: 0, value: 44000, icon: "🔱" },
  { name: "Galleon-Crusher Heavy Alloy", dice: 125, armDef: 55, armStr: 5, wpnDef: 0, wpnStr: 0, value: 49000, icon: "🏗️" },
  { name: "Trench-Lord Heart-Shell", dice: 100, armDef: 54, armStr: 8, wpnDef: 0, wpnStr: 0, value: 55000, icon: "🐚" },
  { name: "Abyssal Star-Forged Ringmail", dice: 100, armDef: 58, armStr: 5, wpnDef: 0, wpnStr: 0, value: 62000, icon: "⭐" },
  { name: "Kraken God Chitin Mantle", dice: 100, armDef: 55, armStr: 12, wpnDef: 0, wpnStr: 0, value: 70000, icon: "🐙" },
  { name: "Poseidon's Royal Cuirass", dice: 100, armDef: 60, armStr: 8, wpnDef: 0, wpnStr: 0, value: 80000, icon: "👑" },
  { name: "Bermuda Singularity Plate", dice: 100, armDef: 64, armStr: 6, wpnDef: 0, wpnStr: 0, value: 92000, icon: "🕳️" },
  { name: "Ocean-Floor Tech Exosuit", dice: 101, armDef: 62, armStr: 10, wpnDef: 0, wpnStr: 0, value: 105000, icon: "🤖" },
  { name: "True-Leviathan Eternal Husk", dice: 101, armDef: 68, armStr: 6, wpnDef: 0, wpnStr: 0, value: 120000, icon: "🐉" },
  { name: "Tidal-Vanishing Shroud", dice: 102, armDef: 60, armStr: 18, wpnDef: 0, wpnStr: 0, value: 140000, icon: "🌫️" },
  { name: "World-Serpent Coiled Carapace", dice: 103, armDef: 72, armStr: 8, wpnDef: 0, wpnStr: 0, value: 165000, icon: "🐍" },
  { name: "Maelstrom Overdrive Endoskeleton", dice: 104, armDef: 70, armStr: 12, wpnDef: 0, wpnStr: 0, value: 195000, icon: "🌀" },
  { name: "Abyssal Sovereign Dreadnought", dice: 105, armDef: 78, armStr: 6, wpnDef: 0, wpnStr: 0, value: 230000, icon: "🔱" },
  { name: "Oceanus Primordial Essence", dice: 105, armDef: 75, armStr: 16, wpnDef: 0, wpnStr: 0, value: 280000, icon: "🔮" },
  { name: "Fisher's Secret Waterproof Apron", dice: 115, armDef: 10, armStr: 99, wpnDef: 0, wpnStr: 0, value: 350000, icon: "🦺" },
  { name: "The Mariana Trench Wall", dice: 115, armDef: 120, armStr: 0, wpnDef: 0, wpnStr: 0, value: 500000, icon: "🧱" },
  { name: "God-Emperor Neptune's Aegis", dice: 115, armDef: 100, armStr: 50, wpnDef: 0, wpnStr: 0, value: 1000000, icon: "👑" }
];