// Dave's 100 Weapons fully calibrated with your custom framework properties
const DAVE_WEAPONS = [
  { name: "Whittled Shiv", dice: 3, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 0, value: 2, icon: "🔪" },
  { name: "Old Cleaver", dice: 4, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 0, value: 5, icon: "🪓" },
  { name: "Rusty Hatchet", dice: 4, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 8, icon: "🪓" },
  { name: "Sharpened Stake", dice: 5, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 0, value: 10, icon: "🪵" },
  { name: "Scrap Iron Dirk", dice: 5, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 12, icon: "🗡️" },
  { name: "Scavenger Club", dice: 6, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 0, value: 14, icon: "🪵" },
  { name: "Blacksmith Reject", dice: 6, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 16, icon: "⚔️" },
  { name: "Rebel Pitchfork", dice: 5, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 18, icon: "🔱" },
  { name: "Poacher Bow", dice: 6, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 22, icon: "🏹" },
  { name: "Copper Gladius", dice: 7, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 25, icon: "⚔️" },
  { name: "Hardwood Cudgel", dice: 8, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 0, value: 28, icon: "🦧" },
  { name: "Militia Spear", dice: 6, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 30, icon: "🔱" },
  { name: "Sailor Grapnel", dice: 7, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 32, icon: "⚓" },
  { name: "Bone Hunting Knife", dice: 5, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 35, icon: "🦴" },
  { name: "Dock Hand Hook", dice: 8, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 38, icon: "🪝" },
  { name: "Brittle Falchion", dice: 9, wpnStr: 0, wpnDef: 0, armStr: 0, armDef: 0, value: 40, icon: "⚔️" },
  { name: "Carved Quarterstaff", dice: 7, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 42, icon: "🪄" },
  { name: "Thief Stiletto", dice: 6, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 45, icon: "🗡️" },
  { name: "Surveyor Chain", dice: 8, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 48, icon: "⛓️" },
  { name: "Bronze Broadsword", dice: 10, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 50, icon: "⚔️" },
  { name: "Black Reed Staff", dice: 8, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 52, icon: "🎋" },
  { name: "Heckler Flail", dice: 9, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 55, icon: "⛓️" },
  { name: "Trapper Hatchet", dice: 7, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 58, icon: "🪓" },
  { name: "Mariner Cutlass", dice: 10, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 62, icon: "⚔️" },
  { name: "Ashen Cane", dice: 9, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 65, icon: "🦯" },
  { name: "Iron Spatha", dice: 11, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 70, icon: "⚔️" },
  { name: "Barbed Pike", dice: 9, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 75, icon: "🔱" },
  { name: "Heavy Spiked Mace", dice: 12, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 80, icon: "🔨" },
  { name: "Stalker Longbow", dice: 10, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 85, icon: "🏹" },
  { name: "Steel Baselard", dice: 8, wpnStr: 7, wpnDef: 0, armStr: 0, armDef: 0, value: 90, icon: "🗡️" },
  { name: "Miner Pickaxe", dice: 11, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 95, icon: "⛏️" },
  { name: "Whirlwind Scythe", dice: 13, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 100, icon: "🪝" },
  { name: "Garrison Halberd", dice: 12, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 110, icon: "🪓" },
  { name: "Deepwater Trident", dice: 11, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 115, icon: "🔱" },
  { name: "Mercenary Claymore", dice: 14, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 125, icon: "⚔️" },
  { name: "Corrupted Kukri", dice: 10, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 130, icon: "🗡️" },
  { name: "Polished War Pick", dice: 12, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 140, icon: "🔨" },
  { name: "Brigand Estoc", dice: 11, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 150, icon: "⚔️" },
  { name: "Ogre Cudgel", dice: 15, wpnStr: 1, wpnDef: 0, armStr: 0, armDef: 0, value: 160, icon: "🪵" },
  { name: "Sentry Partizan", dice: 13, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 175, icon: "🔱" },
  { name: "Tempered Sabre", dice: 12, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 190, icon: "⚔️" },
  { name: "Ranger Recurve", dice: 11, wpnStr: 7, wpnDef: 0, armStr: 0, armDef: 0, value: 200, icon: "🏹" },
  { name: "High-Plains Tomahawk", dice: 10, wpnStr: 9, wpnDef: 0, armStr: 0, armDef: 0, value: 210, icon: "🪓" },
  { name: "Heavy Morningstar", dice: 14, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 225, icon: "🔨" },
  { name: "Duelist Rapier", dice: 9, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 240, icon: "⚔️" },
  { name: "Hardened Greatsword", dice: 16, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 250, icon: "⚔️" },
  { name: "Vanguard Bec-de-Corbin", dice: 14, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 265, icon: "🔨" },
  { name: "Gilded Khopesh", dice: 13, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 280, icon: "⚔️" },
  { name: "Torturer Barbed Whip", dice: 11, wpnStr: 9, wpnDef: 0, armStr: 0, armDef: 0, value: 295, icon: "⛓️" },
  { name: "Bastard Sword", dice: 15, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 310, icon: "⚔️" },
  { name: "Royal Crested Blade", dice: 16, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 330, icon: "⚔️" },
  { name: "Grand Executioner Axe", dice: 18, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 350, icon: "🪓" },
  { name: "Paladin Warhammer", dice: 17, wpnStr: 4, wpnDef: 0, armStr: 0, armDef: 0, value: 375, icon: "🔨" },
  { name: "Nightshade Katar", dice: 12, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 400, icon: "🗡️" },
  { name: "Spiked Flanged Mace", dice: 15, wpnStr: 7, wpnDef: 0, armStr: 0, armDef: 0, value: 420, icon: "🔨" },
  { name: "Cavalry Lance", dice: 16, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 440, icon: "🔱" },
  { name: "Assassin Garrote", dice: 10, wpnStr: 15, wpnDef: 0, armStr: 0, armDef: 0, value: 465, icon: "⛓️" },
  { name: "Heavy Heavy Flail", dice: 17, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 485, icon: "🔨" },
  { name: "Composite Greatbow", dice: 15, wpnStr: 8, wpnDef: 0, armStr: 0, armDef: 0, value: 500, icon: "🏹" },
  { name: "Silver-Inlaid Scimitar", dice: 16, wpnStr: 7, wpnDef: 0, armStr: 0, armDef: 0, value: 525, icon: "⚔️" },
  { name: "Imperial Lochaber Axe", dice: 19, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 550, icon: "🪓" },
  { name: "High-Guard Glaive", dice: 17, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 580, icon: "🔱" },
  { name: "Crimson Rondel", dice: 11, wpnStr: 15, wpnDef: 0, armStr: 0, armDef: 0, value: 600, icon: "🗡️" },
  { name: "Double-Bitted Greataxe", dice: 20, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 630, icon: "🪓" },
  { name: "Gladiator Net & Trident", dice: 14, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 660, icon: "🔱" },
  { name: "Runed Zweihander", dice: 21, wpnStr: 2, wpnDef: 0, armStr: 0, armDef: 0, value: 700, icon: "⚔️" },
  { name: "Judgement Gavel", dice: 18, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 735, icon: "🔨" },
  { name: "Sharpened Katana", dice: 16, wpnStr: 9, wpnDef: 0, armStr: 0, armDef: 0, value: 770, icon: "⚔️" },
  { name: "Cursed Barbed Spear", dice: 15, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 800, icon: "🔱" },
  { name: "Brutal Warmace", dice: 19, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 840, icon: "🔨" },
  { name: "Executioner Greatsword", dice: 22, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 880, icon: "⚔️" },
  { name: "Marauder Cleaver", dice: 18, wpnStr: 8, wpnDef: 0, armStr: 0, armDef: 0, value: 920, icon: "🪓" },
  { name: "Elite Guard Rapier", dice: 12, wpnStr: 17, wpnDef: 0, armStr: 0, armDef: 0, value: 960, icon: "⚔️" },
  { name: "Spiked War Chain", dice: 16, wpnStr: 12, wpnDef: 0, armStr: 0, armDef: 0, value: 1000, icon: "⛓️" },
  { name: "Quartermaster Halberd", dice: 20, wpnStr: 7, wpnDef: 0, armStr: 0, armDef: 0, value: 1050, icon: "🪓" },
  { name: "Arundo Scepter", dice: 18, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 1150, icon: "🎋" },
  { name: "Abyssal Anchor", dice: 22, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 1250, icon: "⚓" },
  { name: "Drack Flightwing Edge", dice: 20, wpnStr: 9, wpnDef: 0, armStr: 0, armDef: 0, value: 1350, icon: "🦅" },
  { name: "Titanite Sledge", dice: 25, wpnStr: 3, wpnDef: 0, armStr: 0, armDef: 0, value: 1500, icon: "🔨" },
  { name: "Wasp-Sting Dagger", dice: 14, wpnStr: 20, wpnDef: 0, armStr: 0, armDef: 0, value: 1650, icon: "🗡️" },
  { name: "Volcanic Firestar", dice: 21, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 1800, icon: "🔥" },
  { name: "Colonial Arc Welder", dice: 23, wpnStr: 9, wpnDef: 0, armStr: 0, armDef: 0, value: 1950, icon: "🤖" },
  { name: "Shadow-Mesh Scythe", dice: 24, wpnStr: 8, wpnDef: 0, armStr: 0, armDef: 0, value: 2100, icon: "🪝" },
  { name: "Bone-Crusher Maul", dice: 26, wpnStr: 6, wpnDef: 0, armStr: 0, armDef: 0, value: 2300, icon: "🦴" },
  { name: "Silver Drake Fang", dice: 22, wpnStr: 12, wpnDef: 0, armStr: 0, armDef: 0, value: 2500, icon: "⚔️" },
  { name: "Stormbolt Javelin", dice: 20, wpnStr: 16, wpnDef: 0, armStr: 0, armDef: 0, value: 2750, icon: "⚡" },
  { name: "Vortex Spellblade", dice: 24, wpnStr: 11, wpnDef: 0, armStr: 0, armDef: 0, value: 3000, icon: "🔮" },
  { name: "Leech-Tooth Saber", dice: 23, wpnStr: 14, wpnDef: 0, armStr: 0, armDef: 0, value: 3300, icon: "🐲" },
  { name: "Ancient Colossus Glaive", dice: 27, wpnStr: 9, wpnDef: 0, armStr: 0, armDef: 0, value: 3600, icon: "🔱" },
  { name: "Dweable Golden Carver", dice: 18, wpnStr: 25, wpnDef: 0, armStr: 0, armDef: 0, value: 4000, icon: "🥇" },
  { name: "Ruinous Great-Axe", dice: 30, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 4500, icon: "🪓" },
  { name: "Eclipse Longbow", dice: 24, wpnStr: 16, wpnDef: 0, armStr: 0, armDef: 0, value: 5000, icon: "🏹" },
  { name: "Dreadlord Claymore", dice: 28, wpnStr: 12, wpnDef: 0, armStr: 0, armDef: 0, value: 5500, icon: "⚔️" },
  { name: "Nebula Morningstar", dice: 26, wpnStr: 17, wpnDef: 0, armStr: 0, armDef: 0, value: 6200, icon: "🔨" },
  { name: "Hellfire Greatsword", dice: 32, wpnStr: 10, wpnDef: 0, armStr: 0, armDef: 0, value: 7000, icon: "🔥" },
  { name: "Spine of the Leech", dice: 25, wpnStr: 22, wpnDef: 0, armStr: 0, armDef: 0, value: 8000, icon: "🐉" },
  { name: "Vanguard Doomsday Pillar", dice: 35, wpnStr: 5, wpnDef: 0, armStr: 0, armDef: 0, value: 9000, icon: "🪵" },
  { name: "Thundercloud Crest", dice: 30, wpnStr: 20, wpnDef: 0, armStr: 0, armDef: 0, value: 10000, icon: "⚡" },
  { name: "Dave's Secret Crowbar", dice: 1, wpnStr: 99, wpnDef: 0, armStr: 0, armDef: 0, value: 15000, icon: "🔧" },
  { name: "Infinity Edge", dice: 50, wpnStr: 50, wpnDef: 0, armStr: 0, armDef: 0, value: 25000, icon: "👑" }
];